### ISSUE TITLE
Research on the required hardware and its costs

### ISSUE THREAD

**Issue by rsgc-dunphy-j** [rsgc-edwards-g/RoomStatusApp#1]
Figuring out how to implement sensors on all the different doors of the school. Will require checking each and wing of the school to see if the doors are different and if we will require a different sensor. Then it is only a matter of building the sensors and testing them out.

**Comment by rsgc-power-r** [comment]
Here are some links that refer to possible hardware that can be used:
Wireless 1 - http://www.instructables.com/id/Wireless-communication-Arduino-RF/?ALLSTEPS
Wireless 2 - http://www.instructables.com/id/RF-315433-MHz-Transmitter-receiver-Module-and-Ardu/?ALLSTEPS
Wifi Shield (Arduino) - https://www.arduino.cc/en/Main/ArduinoWiFiShield
Wifi Shield (Article) - https://www.openhomeautomation.net/monitor-your-home-remotely-using-the-arduino-wifi-shield/

**Comment by rgordonathome** [comment]
This issue requires a label.
