### ISSUE TITLE
Create Mockup of See House Main Floor

### ISSUE THREAD

**Issue by rsgc-edwards-g** [rsgc-edwards-g/RoomStatusApp#10]

**Comment by rsgc-edwards-g** [comment]
![photo on 2015-12-08 at 11 52 am](https://cloud.githubusercontent.com/assets/14296586/11661932/438811f6-9da2-11e5-913d-5a3028c1ae45.jpg)

Unnecessary map of See House main floor

**Comment by rgordonathome** [comment]
If this map was not necessary, why was time spent creating it?

This issue also requires a label.
