### ISSUE TITLE
Main Floor Senior School Paper Prototype

### ISSUE THREAD

**Issue by rsgc-dunphy-j** [rsgc-edwards-g/RoomStatusApp#11]
we need one

**Comment by rgordonathome** [comment]
This issue requires a label.

**Comment by rsgc-dunphy-j** [comment]
![photo on 2015-12-14 at 11 11 am](https://cloud.githubusercontent.com/assets/14296610/11786234/7e9519d2-a253-11e5-9cf1-7a0c02cb5f9f.jpg)
