### ISSUE TITLE
Determine which doors will be monitored

### ISSUE THREAD

**Issue by rsgc-edwards-g** [rsgc-edwards-g/RoomStatusApp#12]

**Comment by rsgc-edwards-g** [comment]
All of the doors in the library have zero room to work with in the area we are hoping to use. Only alternative I can see is on the physical door with a sensor on the frame/other door and a sensor on the door that opens.

**Comment by rsgc-edwards-g** [comment]
All the science labs have enough space to work with in the area we initially wanted to use. That would be six doors on the second floor alone.

**Comment by rgordonathome** [comment]
Graeme, do you have photos of the door frames for these locations? That would help everyone understand fully what you are describing.

**Comment by rgordonathome** [comment]
This issue requires a label.

**Comment by rsgc-dunphy-j** [comment]
It would be hard to get a picture of the space we are working with, but it is a little over an inch wide and about 2 cm deep.

**Comment by rsgc-edwards-g** [comment]
We have decided to monitor the doors to rooms 207, 210 and 211 due to the fact that they don't close automatically, making them useful to our project. We would like to use the cavity at the top of the door to house a distance sensor and its power source. By setting a default "CLOSED" distance, we will be able to tell whether the door is open or closed.
