### ISSUE TITLE
Create Door History Graph

### ISSUE THREAD

**Issue by rsgc-edwards-g** [rsgc-edwards-g/RoomStatusApp#15]
Also include new additions in previously created pages

**Comment by rsgc-edwards-g** [comment]
![photo on 2015-12-12 at 12 08 pm](https://cloud.githubusercontent.com/assets/14296586/11763038/0f250c6e-a0c9-11e5-91d8-21a6232444f4.jpg)

The new graphical representation of door history.

**Comment by rgordonathome** [comment]
This issue requires a label. Suggestion: 'design'
