### ISSUE TITLE
Sketch of "Hover" view for Sr School building

### ISSUE THREAD

**Issue by rsgc-edwards-g** [rsgc-edwards-g/RoomStatusApp#16]
For when the mouse is hovering over a building (specifically the senior school building)

**Comment by rsgc-dunphy-j** [comment]
Completed along with the paper prototype maps

**Comment by rgordonathome** [comment]
This issue cannot be closed without a clear photo or scan of the sketch attached.

**Comment by rgordonathome** [comment]
This issue requires a label.  Suggestion: 'design'

**Comment by rsgc-dunphy-j** [comment]
![photo on 2015-12-14 at 11 12 am](https://cloud.githubusercontent.com/assets/14296610/11786272/a5cea8f6-a253-11e5-8cc6-5ca5d785e295.jpg)
