### ISSUE TITLE
Paper Prototype of Home/Landing Page

### ISSUE THREAD

**Issue by rsgc-edwards-g** [rsgc-edwards-g/RoomStatusApp#2]

**Comment by rsgc-edwards-g** [comment]
![photo on 2015-12-04 at 12 07 pm](https://cloud.githubusercontent.com/assets/14296586/11595867/ab96736c-9a7f-11e5-9270-470681855e1c.jpg)

**Comment by rgordonathome** [comment]
This issue requires a label.
