### ISSUE TITLE
Paper Prototype of Sr. School Map (3rd Floor)

### ISSUE THREAD

**Issue by rsgc-edwards-g** [rsgc-edwards-g/RoomStatusApp#4]

**Comment by rsgc-dunphy-j** [comment]
![flor 3](https://cloud.githubusercontent.com/assets/14296610/11645550/652f8ffc-9d23-11e5-8c3e-736293ca4a26.JPG)

**Comment by rgordonathome** [comment]
This issue requires a label. Suggestion: 'design'
