### ISSUE TITLE
Specific Door History (Paper version)

### ISSUE THREAD

**Issue by rsgc-edwards-g** [rsgc-edwards-g/RoomStatusApp#5]

**Comment by rsgc-edwards-g** [comment]
![photo on 2015-12-05 at 11 14 am](https://cloud.githubusercontent.com/assets/14296586/11608784/9521d640-9b41-11e5-8470-a98b0c7cdc61.jpg)

**Comment by rsgc-edwards-g** [comment]
The door history sample. I've also included a page that shows which doors are open, closed and available.

**Comment by rsgc-edwards-g** [comment]
![photo on 2015-12-05 at 11 15 am](https://cloud.githubusercontent.com/assets/14296586/11608794/b450daa2-9b41-11e5-8276-69e9a352b668.jpg)

**Comment by rgordonathome** [comment]
This issue should have a label: Suggestion: 'design'
